// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eexfpjqxchgoealccfod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVleGZwanF4Y2hnb2VhbGNjZm9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyODQ3MjEsImV4cCI6MjA2Njg2MDcyMX0.GKnasxVRXXSV_UDbKBguDY1KYT8deUZpPP2C4OfxQBE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});